[build]
  # 1) npm install → 2) pip install → 3) 빌드/배포
  command   = "npm install && pip install -r requirements.txt"
  publish   = "static"
  functions = "functions"

[[plugins]]
  package = "netlify-plugin-serverless-wsgi"
  [plugins.inputs]
    app_module     = "functions/api:app"
    python_version = "3.11"
